Mtdsa 6712 RAML for Retrieve Foreign Property Adjustments
hmrc/self-assessment-bsas-api pull request #173
Opened 2020-08-20 08:39 UTC by HarryBaxter

2020-08-20 13:03 UTC, Mbrookesy requested changes

2020-08-20 13:03 UTC, Mbrookesy commented on resources/public/api/conf/2.0/retrieve_foreign_property_adjustments.raml
> +displayName: Retrieve a Foreign Property Business' Summary Adjustments
Unsure if this should or should not have [test only] at the end of the title

2020-08-20 13:19 UTC, HarryBaxter commented on resources/public/api/conf/2.0/examples/adjustments/retrieve_foreign_property_adjustments.json
> +      "href": "/individuals/self-assessment/adjustable-summary/foreign-property/717f3a7a-db8e-11e9-8a34-2a2ae2dbcce4",
It seems to be missing from all examples so I'll add them in

2020-08-24 13:52 UTC, Mbrookesy requested changes

2020-08-24 13:52 UTC, Mbrookesy commented on resources/public/api/conf/2.0/schemas/retrieve_foreign_property_adjustments.json
> +            "example": "/individuals/self-assessment/adjustable-summary/AA123456A"
The example href doesn't seem to include /foreign-property/{bsasId}

2020-08-24 13:57 UTC, Mbrookesy approved these changes

2020-08-26 07:49 UTC, merged