[MTDSA-8256] - Submit Self-Employment Bsas Adjustments Alignments
hmrc/self-assessment-bsas-api pull request #230
Opened 2021-02-25 08:50 UTC by DreamcastKnight

2021-02-25 09:40 UTC, Mbrookesy approved these changes

2021-02-25 14:37 UTC, Mbrookesy requested changes

2021-02-25 14:37 UTC, Mbrookesy commented on it/v2/endpoints/SubmitSelfEmploymentBsasControllerISpec.scala
> +          (UNPROCESSABLE_ENTITY, "INCOMESOURCE_TYPE_NOT_MATCHED", FORBIDDEN, RuleNotSelfEmployment),
The DES side of the BVR errors return 403s and not 500s

2021-03-01 09:00 UTC, Thepworth95 commented on app/v2/models/errors/mtdErrors.scala
> +//object RuleErrorPropertyAdjusted extends MtdError("RULE_UK_PROPERTY_ADJUSTED",
why is this comented out?

2021-03-01 10:41 UTC, Thepworth95 approved these changes

2021-03-01 10:42 UTC, merged