[MTDSA-8548] NRS Connector & Service for NRS in FP BSAS
hmrc/self-assessment-bsas-api pull request #249
Opened 2021-04-13 13:03 UTC by Mbrookesy

2021-04-13 13:46 UTC, james-work-account requested changes

2021-04-13 13:46 UTC, james-work-account commented on test/v2/services/SubmitForeignPropertyBsasNrsProxyServiceSpec.scala
> +        service.submit(nino.toString(), SubmitForeignPropertyBsasRequestBody(None, None))
This isn't a test - you're just running the service function and not comparing it to anything.

2021-04-13 13:46 UTC, james-work-account commented on test/v2/services/SubmitForeignPropertyBsasNrsProxyServiceSpec.scala
> +        service.submit(nino.toString(), SubmitForeignPropertyBsasRequestBody(None, None))
If the other service/s is/are doing the same, it/they needs/need changing too.

2021-04-13 13:46 UTC, james-work-account commented on app/v2/services/SubmitForeignPropertyBsasNrsProxyService.scala
> +  def submit(nino: String, body: SubmitForeignPropertyBsasRequestBody)(implicit hc: HeaderCarrier, ec: ExecutionContext): Unit = {
Change return type to `Future[Unit]`

2021-04-13 13:48 UTC, james-work-account commented on app/v2/services/SubmitForeignPropertyBsasNrsProxyService.scala
> +  def submit(nino: String, body: SubmitForeignPropertyBsasRequestBody)(implicit hc: HeaderCarrier, ec: ExecutionContext): Unit = {
Same for any other services

2021-04-15 10:12 UTC, Nboaram approved these changes

2021-04-15 10:34 UTC, merged